import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import "./Reports.css";
import { API_BASE_URL, authHeaders } from "../../config";

function Reports() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [selectedReport, setSelectedReport] = useState(null);
  const [editReport, setEditReport] = useState(null);
  const [generatedReports, setGeneratedReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const normalizeReport = (item) => {
    const id = item._id || item.id || `RPT-${Date.now()}`;
    return {
      id: String(id),
      name: item.name || "Security Report",
      type: item.type || "Threat Detection",
      date: item.createdAt ? new Date(item.createdAt).toLocaleDateString() : item.date || new Date().toLocaleDateString(),
      status: item.status || "Completed",
      indicator: item.indicator || "",
      risk: item.risk || "Low",
      score: item.score || 0,
      reason: item.reason || "",
      description: item.description || "",
      _source: item._source || "report",
    };
  };

  const loadReports = async () => {
    try {
      setLoading(true);
      const response = await fetch(`${API_BASE_URL}/api/reports`, { headers: authHeaders() });
      const localReports = JSON.parse(localStorage.getItem("generatedReports") || "[]");

      if (!response.ok) {
        throw new Error("Failed to load reports");
      }

      const data = await response.json();
      const serverReports = (data.reports || []).map(normalizeReport);
      const localNormalized = localReports.map(normalizeReport);
      setGeneratedReports([...localNormalized, ...serverReports]);
    } catch (error) {
      console.error("Reports fetch error:", error);
      const localReports = JSON.parse(localStorage.getItem("generatedReports") || "[]");
      setGeneratedReports(localReports.map(normalizeReport));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const allReports = generatedReports.map(normalizeReport);

  const filteredReports = allReports.filter((report) => {
    const matchesSearch =
      String(report.name || "").toLowerCase().includes(search.toLowerCase()) ||
      String(report.id || "").toLowerCase().includes(search.toLowerCase()) ||
      String(report.type || "").toLowerCase().includes(search.toLowerCase());

    const matchesFilter =
      filter === "All" || report.status === filter;

    return matchesSearch && matchesFilter;
  });

  const reportStats = {
    total: allReports.length,
    month: allReports.filter((report) => {
      const parsedDate = new Date(report.date);
      if (Number.isNaN(parsedDate.getTime())) return false;
      const now = new Date();
      return parsedDate.getMonth() === now.getMonth() && parsedDate.getFullYear() === now.getFullYear();
    }).length,
    critical: allReports.filter((report) => String(report.risk || "").toLowerCase() === "critical").length,
    pending: allReports.filter((report) => String(report.status || "").toLowerCase() === "pending").length,
  };

  const getReportContent = (report) => [
    report.name,
    "=".repeat(report.name.length),
    `Report ID: ${report.id}`,
    `Type: ${report.type}`,
    `Date: ${report.date}`,
    `Status: ${report.status}`,
    report.indicator ? `Indicator: ${report.indicator}` : "",
    report.risk ? `Risk: ${report.risk} (${report.score}%)` : "",
    report.reason ? `Assessment: ${report.reason}` : "",
    "",
    "This cybersecurity report was generated by the AI Cyber Threat Intelligence Platform.",
    "Review the report details, correlate related indicators, and record any response actions.",
  ].join("\n");

  const handleDownload = (report) => {
    const file = new Blob([getReportContent(report)], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(file);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.id}-${report.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = (report) => {
    const pdf = new jsPDF();
    const lines = getReportContent(report).split("\n");

    pdf.setFillColor(7, 17, 27);
    pdf.rect(0, 0, 210, 60, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.text(report.name || "Security Report", 14, 24);
    pdf.setFontSize(10);
    pdf.text(`Report ID: ${report.id}`, 14, 34);
    pdf.text(`Type: ${report.type}`, 14, 40);
    pdf.text(`Status: ${report.status}`, 14, 46);

    pdf.setTextColor(24, 38, 52);
    let y = 70;
    lines.slice(1).forEach((line) => {
      if (line.trim()) {
        pdf.setFontSize(11);
        pdf.text(line, 14, y);
        y += 8;
      }
      if (y > 270) {
        pdf.addPage();
        y = 20;
      }
    });

    pdf.save(`${report.id}-${(report.name || "security-report").toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`);
  };

  const handleGenerateReport = () => {
    const reportId = window.prompt("Enter the report ID to download:");

    if (!reportId?.trim()) {
      return;
    }

    const report = allReports.find(
      (item) => String(item.id).toLowerCase() === reportId.trim().toLowerCase()
    );

    if (!report) {
      window.alert(`Report ID ${reportId.trim()} was not found.`);
      return;
    }

    handleDownload(report);
  };

  const handleEditSave = async () => {
    if (!editReport) return;

    try {
      const response = await fetch(`${API_BASE_URL}/api/reports/${editReport.id}`, {
        method: "PUT",
        headers: authHeaders(),
        body: JSON.stringify({
          name: editReport.name,
          type: editReport.type,
          status: editReport.status,
          indicator: editReport.indicator,
          risk: editReport.risk,
          score: Number(editReport.score || 0),
          reason: editReport.reason,
          description: editReport.description,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to update report");
      }

      const localReports = JSON.parse(localStorage.getItem("generatedReports") || "[]");
      const nextLocal = localReports.map((item) => String(item.id || item._id) === String(editReport.id)
        ? { ...item, ...editReport, id: editReport.id }
        : item);
      localStorage.setItem("generatedReports", JSON.stringify(nextLocal));

      await loadReports();
      setEditReport(null);
    } catch (error) {
      console.error("Edit report error:", error);
      window.alert("The report could not be updated right now.");
    }
  };

  const handleDeleteReport = async (reportId) => {
    const shouldDelete = window.confirm("Delete this report?");
    if (!shouldDelete) return;

    try {
      const response = await fetch(`${API_BASE_URL}/api/reports/${reportId}`, {
        method: "DELETE",
        headers: authHeaders(),
      });

      if (!response.ok) {
        throw new Error("Failed to delete report");
      }

      const localReports = JSON.parse(localStorage.getItem("generatedReports") || "[]");
      const filteredLocal = localReports.filter((item) => String(item.id || item._id) !== String(reportId));
      localStorage.setItem("generatedReports", JSON.stringify(filteredLocal));
      await loadReports();
    } catch (error) {
      console.error("Delete report error:", error);
      window.alert("Could not delete the report right now.");
    }
  };

  return (
    <div className="reports-page">

      {/* ================= HEADER ================= */}

      <div className="reports-header">

        <div>
          <h1>Reports</h1>

          <p>
            Generate and manage your cybersecurity reports
          </p>
        </div>

        <button className="generate-report-btn" onClick={handleGenerateReport}>
          <span>+</span>
          Generate Report
        </button>

      </div>


      {/* ================= STAT CARDS ================= */}

      <div className="report-stats">

        <div className="report-stat-card">

          <div className="stat-top">
            <span>Total Reports</span>
            <div className="stat-icon blue">
              📄
            </div>
          </div>

          <h2>{reportStats.total}</h2>

          <p>
            All generated reports
          </p>

        </div>


        <div className="report-stat-card">

          <div className="stat-top">
            <span>Generated This Month</span>
            <div className="stat-icon purple">
              📊
            </div>
          </div>

          <h2>{reportStats.month}</h2>

          <p>
            Reports generated
          </p>

        </div>


        <div className="report-stat-card">

          <div className="stat-top">
            <span>Critical Reports</span>
            <div className="stat-icon red">
              ⚠
            </div>
          </div>

          <h2>{reportStats.critical}</h2>

          <p>
            Require attention
          </p>

        </div>


        <div className="report-stat-card">

          <div className="stat-top">
            <span>Pending Reports</span>
            <div className="stat-icon orange">
              ◷
            </div>
          </div>

          <h2>{reportStats.pending}</h2>

          <p>
            Waiting for generation
          </p>

        </div>

      </div>


      {/* ================= RECENT REPORTS ================= */}

      <div className="recent-reports-section">

        <div className="section-title">

          <div>
            <h2>Recent Reports</h2>

            <p>
              View and manage your latest security reports
            </p>
          </div>

        </div>


        {/* SEARCH + FILTER */}

        <div className="reports-toolbar">

          <div className="report-search">

            <span>⌕</span>

            <input
              type="text"
              placeholder="Search reports..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />

          </div>


          <div className="report-filter">

            <span>Filter:</span>

            <select
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
            >
              <option value="All">All Reports</option>
              <option value="Completed">Completed</option>
              <option value="Pending">Pending</option>
            </select>

          </div>

        </div>


        {/* ================= TABLE ================= */}

        <div className="reports-table-wrapper">

          <table className="reports-table">

            <thead>

              <tr>
                <th>REPORT ID</th>
                <th>REPORT NAME</th>
                <th>TYPE</th>
                <th>DATE</th>
                <th>STATUS</th>
                <th>ACTIONS</th>
              </tr>

            </thead>


            <tbody>

              {filteredReports.length > 0 ? (

                filteredReports.map((report) => (

                  <tr key={report.id}>

                    <td>
                      <span className="report-id">
                        {report.id}
                      </span>
                    </td>


                    <td>

                      <div className="report-name">

                        <div className="document-icon">
                          📄
                        </div>

                        <div>

                          <strong>
                            {report.name}
                          </strong>

                          <small>
                            Generated security report
                          </small>

                        </div>

                      </div>

                    </td>


                    <td>
                      <span className="report-type">
                        {report.type}
                      </span>
                    </td>


                    <td>
                      <span className="report-date">
                        {report.date}
                      </span>
                    </td>


                    <td>

                      <span
                        className={`report-status ${
                          report.status.toLowerCase()
                        }`}
                      >

                        <span className="status-dot-small"></span>

                        {report.status}

                      </span>

                    </td>


                    <td>

                      <div className="report-actions">

                        <button className="view-btn" onClick={() => setSelectedReport(report)}>
                          View
                        </button>

                        <button className="edit-btn" onClick={() => setEditReport({ ...report })} title={`Edit ${report.id}`}>
                          Edit
                        </button>

                        <button className="download-btn" onClick={() => handleDownload(report)} title={`Download ${report.id}`}>
                          ↓
                        </button>
                        <button className="pdf-btn" onClick={() => handleExportPdf(report)} title={`Export PDF ${report.id}`}>
                          PDF
                        </button>
                        <button className="delete-btn" onClick={() => handleDeleteReport(report.id)} title={`Delete ${report.id}`}>
                          ✕
                        </button>

                      </div>

                    </td>

                  </tr>

                ))

              ) : (

                <tr>

                  <td
                    colSpan="6"
                    className="no-reports"
                  >
                    No reports found
                  </td>

                </tr>

              )}

            </tbody>

          </table>

        </div>

      </div>

      {selectedReport && (
        <div className="report-modal-backdrop" onClick={() => setSelectedReport(null)}>
          <section className="report-modal" role="dialog" aria-modal="true" aria-labelledby="report-modal-title" onClick={(event) => event.stopPropagation()}>
            <div className="report-modal-header">
              <div>
                <span>{selectedReport.id}</span>
                <h2 id="report-modal-title">{selectedReport.name}</h2>
              </div>
              <button className="report-modal-close" onClick={() => setSelectedReport(null)} aria-label="Close report">×</button>
            </div>
            <div className="report-modal-details">
              <div><span>Report type</span><strong>{selectedReport.type}</strong></div>
              <div><span>Generated</span><strong>{selectedReport.date}</strong></div>
              <div><span>Status</span><strong>{selectedReport.status}</strong></div>
            </div>
            <p className="report-modal-summary">This report is ready to review. Use the report ID <strong>{selectedReport.id}</strong> when referencing this security record.</p>
            <button className="report-modal-download" onClick={() => handleDownload(selectedReport)}>Download {selectedReport.id}</button>
          </section>
        </div>
      )}

      {editReport && (
        <div className="report-modal-backdrop" onClick={() => setEditReport(null)}>
          <section className="report-edit-modal" role="dialog" aria-modal="true" aria-labelledby="report-edit-title" onClick={(event) => event.stopPropagation()}>
            <div className="report-modal-header">
              <div>
                <span>{editReport.id}</span>
                <h2 id="report-edit-title">Edit report</h2>
              </div>
              <button className="report-modal-close" onClick={() => setEditReport(null)} aria-label="Close edit report">×</button>
            </div>

            <div className="report-edit-form">
              <label>
                <span>Report name</span>
                <input value={editReport.name} onChange={(event) => setEditReport({ ...editReport, name: event.target.value })} />
              </label>

              <label>
                <span>Type</span>
                <input value={editReport.type} onChange={(event) => setEditReport({ ...editReport, type: event.target.value })} />
              </label>

              <label>
                <span>Status</span>
                <select value={editReport.status} onChange={(event) => setEditReport({ ...editReport, status: event.target.value })}>
                  <option value="Completed">Completed</option>
                  <option value="Pending">Pending</option>
                </select>
              </label>

              <label>
                <span>Indicator</span>
                <input value={editReport.indicator} onChange={(event) => setEditReport({ ...editReport, indicator: event.target.value })} />
              </label>

              <label>
                <span>Risk</span>
                <select value={editReport.risk} onChange={(event) => setEditReport({ ...editReport, risk: event.target.value })}>
                  <option value="Low">Low</option>
                  <option value="Medium">Medium</option>
                  <option value="High">High</option>
                  <option value="Critical">Critical</option>
                </select>
              </label>

              <label>
                <span>Score</span>
                <input type="number" min="0" max="100" value={editReport.score || 0} onChange={(event) => setEditReport({ ...editReport, score: Number(event.target.value) })} />
              </label>

              <label className="full-width">
                <span>Assessment</span>
                <textarea rows="3" value={editReport.reason} onChange={(event) => setEditReport({ ...editReport, reason: event.target.value })} />
              </label>

              <label className="full-width">
                <span>Description</span>
                <textarea rows="3" value={editReport.description} onChange={(event) => setEditReport({ ...editReport, description: event.target.value })} />
              </label>
            </div>

            <div className="report-edit-actions">
              <button className="secondary-action" onClick={() => setEditReport(null)}>Cancel</button>
              <button className="primary-action" onClick={handleEditSave}>Save changes</button>
            </div>
          </section>
        </div>
      )}

    </div>
  );
}

export default Reports;